### ISSUE TITLE
Orders using Stripe payment method displayed as empty in the backend

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio-contrib/solidus_stripe#251]
**To Reproduce**

1. Complete an order using Stripe as the payment method
2. Go to the admin panel and select the order
3. Go to the "Cart" & "Shipping" sections

**Current behavior**
The cart is empty, and there's no line item to ship.

**Expected behavior**
We should be able to see line items from the backend, just like with orders payed with Credit Card or Check.

**Screencast**

https://user-images.githubusercontent.com/52650/227881479-0c3eb36f-52d2-4828-8774-f68ad24129b6.mp4

**Additional context**
The order looks ok at the model layer, as `order.line_items` works as expected. It also possible to generate a return and pick the associated line items from the backend.

**Comment by rainerdema** [comment]
The problem is connected to an API call in `solidus_backend` that suggests that we're missing a `_stripe.json.jbuilder` partial needed for Stripe integration in `solidus_api` (similar to [this one](https://github.com/solidusio/solidus/blob/master/api/app/views/spree/api/payments/source_views/_store_credit.json.jbuilder)):
```
Request URL: http://localhost:3000/api/orders/R870698049
Request Method: GET
Status Code: 500 Internal Server Error
Response: Missing partial spree/api/payments/source_views/_stripe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}.
```
![Screenshot 2023-03-27 at 16 12 42](https://user-images.githubusercontent.com/19948291/227965795-81c421c2-7f30-46cd-b701-d4c1685c852d.png)
![Screenshot 2023-03-27 at 16 12 31](https://user-images.githubusercontent.com/19948291/227965813-fa309636-6260-428b-823d-b83ae2ba6203.png)
